const LGD_TO_STATE = {
    "1": {
        state_name: "JAMMU AND KASHMIR",
        districts: {
            "1": "ANANTNAG",
            "2": "Budgam",
            "3": "BARAMULLA",
            "4": "DODA",
            "5": "JAMMU",
            "7": "KATHUA",
            "8": "KUPWARA",
            "10": "POONCH",
            "11": "PULWAMA",
            "12": "RAJOURI",
            "13": "SRINAGAR",
            "14": "UDHAMPUR",
            "620": "KISHTWAR",
            "621": "RAMBAN",
            "622": "KULGAM",
            "623": "BANDIPORA",
            "624": "SAMBA",
            "625": "SHOPIAN",
            "626": "GANDERBAL",
            "627": "REASI"
        }
    },
    "2": {
        state_name: "HIMACHAL PRADESH",
        districts: {
            "15": "BILASPUR",
            "16": "CHAMBA",
            "17": "HAMIRPUR",
            "18": "KANGRA",
            "19": "KINNAUR",
            "20": "KULLU",
            "21": "LAHUL AND SPITI",
            "22": "MANDI",
            "23": "SHIMLA",
            "24": "SIRMAUR",
            "25": "SOLAN",
            "26": "UNA"
        }
    },
    "3": {
        state_name: "PUNJAB",
        districts: {
            "27": "AMRITSAR",
            "28": "BATHINDA",
            "29": "FARIDKOT",
            "30": "FATEHGARH SAHIB",
            "31": "FEROZEPUR",
            "32": "GURDASPUR",
            "33": "HOSHIARPUR",
            "34": "JALANDHAR",
            "35": "KAPURTHALA",
            "36": "LUDHIANA",
            "37": "MANSA",
            "38": "MOGA",
            "39": "SRI MUKTSAR SAHIB",
            "40": "Shahid Bhagat Singh Nagar",
            "41": "PATIALA",
            "42": "RUPNAGAR",
            "43": "SANGRUR",
            "605": "BARNALA",
            "608": "S.A.S Nagar",
            "609": "Tarn Taran",
            "651": "FAZILKA",
            "662": "PATHANKOT",
            "737": "MALERKOTLA"
        }
    },
    "4": {
        state_name: "CHANDIGARH",
        districts: {}
    },
    "5": {
        state_name: "UTTARAKHAND",
        districts: {
            "45": "ALMORA",
            "46": "BAGESHWAR",
            "47": "CHAMOLI",
            "48": "CHAMPAWAT",
            "49": "DEHRADUN",
            "50": "HARIDWAR",
            "51": "NAINITAL",
            "52": "PAURI GARHWAL",
            "53": "PITHORAGARH",
            "54": "RUDRA PRAYAG",
            "55": "TEHRI GARHWAL",
            "56": "UDAM SINGH NAGAR",
            "57": "UTTAR KASHI"
        }
    },
    "6": {
        state_name: "HARYANA",
        districts: {
            "58": "AMBALA",
            "59": "BHIWANI",
            "60": "FARIDABAD",
            "61": "FATEHABAD",
            "62": "GURUGRAM",
            "63": "HISAR",
            "64": "JHAJJAR",
            "65": "JIND",
            "66": "KAITHAL",
            "67": "KARNAL",
            "68": "KURUKSHETRA",
            "69": "MAHENDRAGARH",
            "70": "PANCHKULA",
            "71": "PANIPAT",
            "72": "REWARI",
            "73": "ROHTAK",
            "74": "SIRSA",
            "75": "SONIPAT",
            "76": "YAMUNANAGAR",
            "604": "NUH",
            "619": "PALWAL",
            "701": "CHARKI DADRI"
        }
    },
    "7": {
        state_name: "DELHI",
        districts: {
            "77": "CENTRAL",
            "78": "EAST",
            "79": "NEW DELHI",
            "80": "NORTH",
            "81": "NORTH EAST",
            "82": "NORTH WEST",
            "83": "SOUTH",
            "84": "SOUTH WEST",
            "85": "WEST",
            "670": "South East",
            "671": "SHAHDARA",
        }
    },
    "8": {
        state_name: "RAJASTHAN",
        districts: {
            "86": "AJMER",
            "87": "ALWAR",
            "88": "BANSWARA",
            "89": "BARAN",
            "90": "BARMER",
            "91": "BHARATPUR",
            "92": "BHILWARA",
            "93": "BIKANER",
            "94": "BUNDI",
            "95": "CHITTORGARH",
            "96": "CHURU",
            "97": "DAUSA",
            "98": "DHOLPUR",
            "99": "DUNGARPUR",
            "100": "GANGANAGAR",
            "101": "HANUMANGARH",
            "102": "JAIPUR",
            "103": "JAIPUR",
            "104": "JALORE",
            "105": "JHALAWAR",
            "106": "JHUNJHUNU",
            "107": "JODHPUR",
            "108": "KARAULI",
            "109": "KOTA",
            "110": "NAGAUR",
            "111": "PALI",
            "112": "RAJSAMAND",
            "113": "SAWAI MADHOPUR",
            "114": "SIKAR",
            "115": "SIROHI",
            "116": "TONK",
            "117": "UDAIPUR",
            "629": "PRATAPGARH",
            "772": "Phalodi",
            "774": "Beawar",
            "768": "Didwana-Kuchaman",
            "782": "Kotputli-Behror",
            "777": "Salumbar",
            "775": "Balotra",
            "767": "Deeg",
            "770": "Khairthal-Tijara"
        }
    },
    "9": {
        state_name: "UTTAR PRADESH",
        districts: {
            "118": "AGRA",
            "119": "ALIGARH",
            "120": "PRAYAGRAJ",
            "121": "AMBEDKAR NAGAR",
            "122": "AURAIYA",
            "123": "AZAMGARH",
            "124": "BAGHPAT",
            "125": "BAHRAICH",
            "126": "BALLIA",
            "127": "BALRAMPUR",
            "128": "BANDA",
            "129": "BARABANKI",
            "130": "BAREILLY",
            "131": "BASTI",
            "132": "BIJNOR",
            "133": "BUDAUN",
            "134": "BULANDSHAHR",
            "135": "CHANDAULI",
            "136": "CHITRAKOOT",
            "137": "DEORIA",
            "138": "ETAH",
            "139": "ETAWAH",
            "140": "AYODHYA",
            "141": "FARRUKHABAD",
            "142": "FATEHPUR",
            "143": "FIROZABAD",
            "144": "GAUTAM BUDDHA NAGAR",
            "145": "GHAZIABAD",
            "146": "GHAZIPUR",
            "147": "GONDA",
            "148": "GORAKHPUR",
            "149": "HAMIRPUR",
            "150": "HARDOI",
            "151": "JALAUN",
            "152": "JAUNPUR",
            "153": "JHANSI",
            "154": "AMROHA",
            "155": "KANNAUJ",
            "156": "KANPUR DEHAT",
            "157": "KANPUR NAGAR",
            "158": "KAUSHAMBI",
            "159": "KHERI",
            "160": "KUSHI NAGAR",
            "161": "LALITPUR",
            "162": "LUCKNOW",
            "163": "HATHRAS",
            "164": "MAHARAJGANJ",
            "165": "MAHOBA",
            "166": "MAINPURI",
            "167": "MATHURA",
            "168": "MAU",
            "169": "MEERUT",
            "170": "MIRZAPUR",
            "171": "MORADABAD",
            "172": "MUZAFFARNAGAR",
            "173": "PILIBHIT",
            "174": "PRATAPGARH",
            "175": "RAE BARELI",
            "176": "RAMPUR",
            "177": "SAHARANPUR",
            "178": "SANT KABEER NAGAR",
            "179": "BHADOHI",
            "180": "SHAHJAHANPUR",
            "181": "SHRAVASTI",
            "182": "SIDDHARTH NAGAR",
            "183": "SITAPUR",
            "184": "SONBHADRA",
            "185": "SULTANPUR",
            "186": "UNNAO",
            "187": "VARANASI",
            "633": "Kasganj",
            "640": "Amethi",
            "659": "SAMBHAL",
            "660": "SHAMLI",
            "661": "HAPUR"
        }
    },
    "10": {
        state_name: "BIHAR",
        districts: {
            "188": "ARARIA",
            "189": "AURANGABAD",
            "190": "BANKA",
            "191": "BEGUSARAI",
            "192": "BHAGALPUR",
            "193": "BHOJPUR",
            "194": "BUXAR",
            "195": "DARBHANGA",
            "196": "GAYA",
            "197": "GOPALGANJ",
            "198": "JAMUI",
            "199": "JEHANABAD",
            "200": "KAIMUR (BHABUA)",
            "201": "KATIHAR",
            "202": "KHAGARIA",
            "203": "KISHANGANJ",
            "204": "LAKHISARAI",
            "205": "MADHEPURA",
            "206": "MADHUBANI",
            "207": "MUNGER",
            "208": "MUZAFFARPUR",
            "209": "NALANDA",
            "210": "NAWADA",
            "211": "PASHCHIM CHAMPARAN",
            "212": "PATNA",
            "213": "PURBI CHAMPARAN",
            "214": "PURNIA",
            "215": "ROHTAS",
            "216": "SAHARSA",
            "217": "SAMASTIPUR",
            "218": "SARAN",
            "219": "SHEIKHPURA",
            "220": "SHEOHAR",
            "221": "SITAMARHI",
            "222": "SIWAN",
            "223": "SUPAUL",
            "224": "VAISHALI",
            "611": "ARWAL",
        }
    },
    "11": {
        state_name: "SIKKIM",
        districts: {
            "225": "Gangtok",
            "226": "Mangan",
            "227": "Namchi",
            "228": "Gyalshing",
            "741": "Pakyong",
            "742": "Soreng",
        }
    },
    "12": {
        state_name: "ARUNACHAL PRADESH",
        districts: {
            "229": "CHANGLANG",
            "230": "DIBANG VALLEY",
            "231": "EAST KAMENG",
            "232": "EAST SIANG",
            "233": "KURUNG KUMEY",
            "234": "LOHIT",
            "235": "LOWER DIBANG VALLEY",
            "236": "LOWER SUBANSIRI",
            "237": "PAPUM PARE",
            "238": "TAWANG",
            "239": "TIRAP",
            "240": "UPPER SIANG",
            "241": "UPPER SUBANSIRI",
            "242": "WEST KAMENG",
            "243": "WEST SIANG",
            "628": "ANJAW",
            "666": "LONGDING",
            "677": "KRA DAADI",
            "678": "NAMSAI",
            "679": "SIANG",
            "718": "KAMLE",
            "719": "LOWER SIANG",
            "723": "PAKKE KESSANG",
            "724": "LEPARADA",
            "725": "SHI YOMI",
        }
    },
    "13": {
        state_name: "NAGALAND",
        districts: {
            "244": "DIMAPUR",
            "245": "KOHIMA",
            "246": "MOKOKCHUNG",
            "247": "MON",
            "248": "PHEK",
            "249": "TUENSANG",
            "250": "WOKHA",
            "251": "ZUNHEBOTO",
            "613": "PEREN",
            "614": "KIPHIRE",
            "615": "LONGLENG",
            "736": "Noklak",
            "757": "Tseminyu",
            "758": "Chumoukedima"
        }
    },
    "14": {
        state_name: "MANIPUR",
        districts: {
            "252": "BISHNUPUR",
            "253": "CHANDEL",
            "254": "CHURACHANDPUR",
            "255": "IMPHAL EAST",
            "256": "IMPHAL WEST",
            "257": "SENAPATI",
            "258": "TAMENGLONG",
            "259": "THOUBAL",
            "260": "UKHRUL",
            "711": "KAKCHING",
            "712": "KAKCHING",
            "713": "JIRIBAM",
            "714": "NONEY",
            "715": "PHERZAWL",
            "716": "TENGNOUPAL",
            "717": "KAMJONG",
        }
    },
    "15": {
        state_name: "MIZORAM",
        districts: {
            "261": "AIZAWL",
            "262": "CHAMPHAI",
            "263": "KOLASIB",
            "264": "LAWNGTLAI",
            "265": "LUNGLEI",
            "266": "MAMIT",
            "267": "SAIHA",
            "268": "SERCHHIP",
            "726": "Hnahthial",
            "727": "SAITUAL",
            "728": "KHAWZAWL"
        }
    },
    "16": {
        state_name: "TRIPURA",
        districts: {
            "269": "Dhalai",
            "270": "North Tripura",
            "271": "South Tripura",
            "272": "West Tripura",
            "652": "Khowai",
            "653": "Sepahijala",
            "654": "Gomati",
            "655": "Unakoti",
        }
    },
    "17": {
        state_name: "MEGHALAYA",
        districts: {
            "273": "EAST GARO HILLS",
            "274": "NEAST KHASI HILLS",
            "275": "WEST JAINTIA HILLS",
            "276": "RI BHOI",
            "277": "SOUTH GARO HILLS",
            "278": "WEST GARO HILLS",
            "279": "WEST KHASI HILLS",
            "656": "NORTH GARO HILLS",
            "657": "EAST JAINTIA HILLS",
            "658": "SOUTH WEST KHASI HILLS",
            "663": "SOUTH WEST GARO HILLS",
            "740": "EASTERN WEST KHASI HILLS",
        }
    },
    "18": {
        state_name: "ASSAM",
        districts: {
            "280": "BARPETA",
            "281": "BONGAIGAON",
            "282": "CACHAR",
            "283": "DARRANG",
            "284": "DHEMAJI",
            "285": "DHUBRI",
            "286": "DIBRUGARH",
            "287": "GOALPARA",
            "288": "GOLAGHAT",
            "289": "HAILAKANDI",
            "290": "JORHAT",
            "291": "KAMRUP",
            "292": "KARBI ANGLONG",
            "293": "KARIMGANJ",
            "294": "KOKRAJHAR",
            "295": "LAKHIMPUR",
            "296": "MARIGAON",
            "297": "NAGAON",
            "298": "NALBARI",
            "299": "DIMA HASAO",
            "300": "SIVASAGAR",
            "301": "SONITPUR",
            "302": "TINSUKIA",
            "612": "CHIRANG",
            "616": "BAKSA",
            "617": "UDALGURI",
            "618": "KAMRUP METRO",
            "705": "Biswanath",
            "706": "MAJULI",
            "707": "SOUTH SALMARA MANCACHAR",
            "708": "CHARAIDEO",
            "709": "HOJAI",
            "710": "WEST KARBI ANGLONG",
            "739": "BAJALI",
            "756": "TAMULPUR",
        }
    },
    "19": {
        state_name: "WEST BENGAL",
        districts: {
            "303": "24 PARAGANAS NORTH",
            "304": "24 PARAGANAS SOUTH",
            "305": "BANKURA",
            "306": "PURBA BARDHAMAN",
            "307": "BIRBHUM",
            "308": "COOCHBEHAR",
            "309": "DARJEELING",
            "310": "DINAJPUR DAKSHIN",
            "311": "DINAJPUR UTTAR",
            "312": "HOOGHLY",
            "313": "HOWRAH",
            "314": "JALPAIGURI",
            "316": "MALDAH",
            "317": "MEDINIPUR EAST",
            "318": "MEDINIPUR WEST",
            "319": "MURSHIDABAD",
            "320": "NADIA",
            "321": "PURULIA",
            "664": "Alipurduar",
            "702": "KALIMPONG",
            "703": "KALIMPONG",
            "704": "PASCHIM BARDHAMAN",
        }
    },
    "20": {
        state_name: "JHARKHAND",
        districts: {
            "322": "BOKARO",
            "323": "BOKARO",
            "324": "DEOGHAR",
            "325": "DEOGHAR",
            "326": "DUMKA",
            "327": "EAST SINGHBUM",
            "328": "GARHWA",
            "329": "GIRIDIH",
            "330": "GODDA",
            "331": "GUMLA",
            "332": "HAZARIBAGH",
            "333": "JAMTARA",
            "334": "KODERMA",
            "335": "LATEHAR",
            "336": "LOHARDAGA",
            "337": "PAKUR",
            "338": "PALAMU",
            "339": "RANCHI",
            "340": "SAHEBGANJ",
            "341": "SARAIKELA KHARSAWAN",
            "342": "SIMDEGA",
            "343": "WEST SINGHBHUM",
            "606": "KHUNTI",
            "607": "RAMGARH",
        }
    },
    "21": {
        state_name: "ODISHA",
        districts: {
            "369": "PURI",
            "344": "ANUGUL",
            "345": "BALANGIR",
            "346": "BALESHWAR",
            "347": "BARGARH",
            "348": "BHADRAK",
            "349": "BOUDH",
            "350": "CUTTACK",
            "351": "DEOGARH",
            "352": "DHENKANAL",
            "353": "GAJAPATI",
            "354": "GANJAM",
            "355": "JAGATSINGHAPUR",
            "356": "JAJAPUR",
            "357": "JHARSUGUDA",
            "358": "KALAHANDI",
            "359": "KANDHAMAL",
            "360": "KENDRAPARA",
            "361": "KENDUJHAR",
            "362": "KHORDHA",
            "363": "KORAPUT",
            "364": "MALKANGIRI",
            "365": "MAYURBHANJ",
            "366": "NABARANGPUR",
            "367": "NAYAGARH",
            "368": "NUAPADA",
            "370": "RAYAGADA",
            "371": "SAMBALPUR",
            "372": "SONEPUR",
            "373": "SUNDARGARH",
        }
    },
    "22": {
        state_name: "CHHATTISGARH",
        districts: {
            "374": "BASTAR",
            "375": "BILASPUR",
            "376": "DANTEWADA",
            "377": "DHAMTARI",
            "378": "DURG",
            "379": "JANJGIR-CHAMPA",
            "380": "JASHPUR",
            "381": "KANKER",
            "382": "KABIRDHAM",
            "383": "KORBA",
            "384": "KOREA",
            "385": "MAHASAMUND",
            "386": "RAIGARH",
            "387": "RAIPUR",
            "388": "RAJNANDGAON",
            "389": "SURGUJA",
            "636": "BIJAPUR",
            "637": "NARAYANPUR",
            "642": "SUKMA",
            "643": "KONDAGAON",
            "644": "BALODA BAZAR",
            "645": "GARIYABAND",
            "646": "BALOD",
            "647": "MUNGELI",
            "648": "SURAJPUR",
            "649": "BALRAMPUR",
            "650": "BEMETARA",
            "734": "Gaurella Pendra Marwahi",
            "759": "KHAIRGARH CHHUIKHADAN GANDAI",
            "760": "MANENDRAGARH CHIRIMIRI BHARATPUR",
            "761": "MOHLA MANPUR AMBAGARH CHOUKI",
            "762": "SAKTI",
            "763": "SARANGARH BILAIGARH"
        }
    },
    "23": {
        state_name: "MADHYA PRADESH",
        districts: {
            "390": "ANUPPUR",
            "391": "ASHOKNAGAR",
            "392": "BALAGHAT",
            "393": "BARWANI",
            "394": "BETUL",
            "395": "BHIND",
            "396": "BHOPAL",
            "397": "BURHANPUR",
            "398": "CHHATARPUR",
            "399": "CHHINDWARA",
            "400": "DAMOH",
            "401": "DATIA",
            "402": "DEWAS",
            "403": "DHAR",
            "404": "DINDORI",
            "405": "EAST NIMAR",
            "406": "GUNA",
            "407": "GWALIOR",
            "408": "HARDA",
            "409": "NARMADAPURAM",
            "410": "INDORE",
            "411": "JABALPUR",
            "412": "JHABUA",
            "413": "KATNI",
            "414": "KHARGONE",
            "415": "MANDLA",
            "416": "MANDSAUR",
            "417": "MORENA",
            "418": "NARSINGHPUR",
            "419": "NEEMUCH",
            "420": "PANNA",
            "421": "RAISEN",
            "422": "RAJGARH",
            "423": "RATLAM",
            "424": "REWA",
            "425": "SAGAR",
            "426": "SATNA",
            "427": "SEHORE",
            "428": "SEONI",
            "429": "SHAHDOL",
            "430": "SHAJAPUR",
            "431": "SHEOPUR",
            "432": "SHIVPURI",
            "433": "SIDHI",
            "434": "TIKAMGARH",
            "435": "UJJAIN",
            "436": "UMARIA",
            "437": "VIDISHA",
            "438": "SINGRAULI",
            "439": "ALIRAJPUR",
            "667": "AGAR MALWA",
            "766": "MAUGANJ",
            "785": "Pandhurna",
            "784": "Maihar",
        }
    },
    "24": {
        state_name: "GUJARAT",
        districts: {
            "439": "AMRELI",
            "440": "ANAND",
            "441": "BANAS KANTHA",
            "442": "BHARUCH",
            "443": "BHAVNAGAR",
            "444": "DANG",
            "445": "DOHAD",
            "446": "GANDHINAGAR",
            "447": "JAMNAGAR",
            "448": "JUNAGADH",
            "449": "KACHCHH",
            "450": "KHEDA",
            "451": "MAHESANA",
            "452": "NARMADA",
            "453": "NAVSARI",
            "454": "PANCH MAHALS",
            "455": "PATAN",
            "456": "PORBANDAR",
            "457": "RAJKOT",
            "458": "SABAR KANTHA",
            "459": "SURAT",
            "460": "SURENDRANAGAR",
            "461": "VADODARA",
            "462": "VALSAD",
            "641": "TAPI",
            "668": "CHHOTAUDEPUR",
            "669": "Mahisagar",
            "672": "ARVALLI",
            "673": "MORBI",
            "674": "DEVBHUMI DWARKA",
            "675": "GIR SOMNATH",
            "676": "BOTAD",
            "438": "AHMEDABAD",
        }
    },
    "25": {
        state_name: "Daman & Diu",
        districts: {}
    },
    "27": {
        state_name: "Maharashtra",
        districts: {
            "466": "AHMEDNAGAR",
            "467": "AKOLA",
            "468": "AMRAVATI",
            "469": "AURANGABAD",
            "470": "BEED",
            "471": "BHANDARA",
            "472": "BULDHANA",
            "473": "CHANDRAPUR",
            "474": "DHULE",
            "475": "GADCHIROLI",
            "476": "GONDIA",
            "477": "HINGOLI",
            "478": "JALGAON",
            "479": "JALNA",
            "480": "KOLHAPUR",
            "481": "LATUR",
            "483": "MUMBAI SUBURBAN",
            "484": "NAGPUR",
            "485": "NANDED",
            "486": "NANDURBAR",
            "487": "NASHIK",
            "488": "OSMANABAD",
            "489": "PARBHANI",
            "490": "PUNE",
            "491": "RAIGAD",
            "492": "RATNAGIRI",
            "493": "SANGLI",
            "494": "SATARA",
            "495": "SINDHUDURG",
            "496": "SOLAPUR",
            "497": "THANE",
            "498": "WARDHA",
            "499": "WASHIM",
            "500": "YAVATMAL",
            "665": "PALGHAR",
        }
    },
    "28": {
        state_name: "ANDHRA PRADESH",
        districts: {
            "502": "ANANTAPUR",
            "503": "CHITTOOR",
            "504": "Y.S.R.",
            "505": "EAST GODAVARI",
            "506": "GUNTUR",
            "510": "KRISHNA",
            "511": "KURNOOL",
            "515": "SPSR NELLORE",
            "517": "PRAKASAM",
            "519": "SRIKAKULAM",
            "520": "VISAKHAPATANAM",
            "521": "VIZIANAGARAM",
            "523": "WEST GODAVARI",
            "743": "Parvathipuram Manyam",
            "744": "Anakapalli",
            "745": "Alluri Sitharama Raju",
            "746": "Kakinada",
            "747": "Konaseema",
            "748": "Eluru",
            "749": "NTR",
            "750": "Bapatla",
            "751": "Palnadu",
            "752": "Tirupati",
            "753": "Annamayya",
            "754": "Sri Sathya Sai",
            "755": "Nandyal",
        }
    },
    "29": {
        state_name: "KARNATAKA",
        districts: {
            "524": "BAGALKOTE",
            "525": "BENGALURU URBAN",
            "526": "BENGALURU RURAL",
            "527": "BELAGAVI",
            "528": "BALLARI",
            "529": "BIDAR",
            "530": "VIJAYAPURA",
            "531": "CHAMARAJANAGARA",
            "532": "CHIKKAMAGALURU",
            "533": "CHITRADURGA",
            "534": "DAKSHINA KANNADA",
            "535": "DAVANGERE",
            "536": "DHARWAD",
            "537": "GADAG",
            "538": "KALABURAGI",
            "539": "HASSAN",
            "540": "HAVERI",
            "541": "KODAGU",
            "542": "KOLAR",
            "543": "KOPPAL",
            "544": "MANDYA",
            "545": "MYSURU",
            "546": "RAICHUR",
            "547": "SHIVAMOGGA",
            "548": "TUMAKURU",
            "549": "UDUPI",
            "550": "UTTARA KANNADA",
            "630": "CHIKKABALLAPURA",
            "631": "RAMANAGARA",
            "635": "YADGIR",
            "738": "VIJAYANAGAR"
        }
    },
    "30": {
        state_name: "GOA",
        districts: {
            "551": "NORTH GOA",
            "552": "SOUTH GOA",
        }
    },
    "31": {
        state_name: "LAKSHADWEEP",
        districts: {
            "553": "LAKSHADWEEP DISTRICT",
        }
    },
    "32": {
        state_name: "KERALA",
        districts: {
            "554": "ALAPPUZHA",
            "555": "ERNAKULAM",
            "556": "IDUKKI",
            "557": "KANNUR",
            "558": "KASARAGOD",
            "559": "KOLLAM",
            "560": "KOTTAYAM",
            "561": "KOZHIKODE",
            "562": "MALAPPURAM",
            "563": "PALAKKAD",
            "564": "PATHANAMTHITTA",
            "565": "THIRUVANANTHAPURAM",
            "566": "THRISSUR",
            "567": "WAYANAD"
        }
    },
    "33": {
        state_name: "TAMIL NADU",
        districts: {
            "568": "CHENNAI",
            "569": "COIMBATORE",
            "570": "CUDDALORE",
            "571": "DHARMAPURI",
            "572": "DINDIGUL",
            "573": "ERODE",
            "574": "KANCHIPURAM",
            "575": "KANNIYAKUMARI",
            "576": "KARUR",
            "577": "KRISHNAGIRI",
            "578": "MADURAI",
            "579": "NAGAPATTINAM",
            "580": "NAMAKKAL",
            "581": "PERAMBALUR",
            "582": "PUDUKKOTTAI",
            "583": "RAMANATHAPURAM",
            "584": "SALEM",
            "585": "SIVAGANGA",
            "586": "THANJAVUR",
            "587": "THE NILGIRIS",
            "588": "THENI",
            "589": "THIRUVALLUR",
            "590": "THIRUVARUR",
            "591": "TIRUCHIRAPPALLI",
            "592": "TIRUNELVELI",
            "593": "TIRUVANNAMALAI",
            "594": "TUTICORIN",
            "595": "VELLORE",
            "596": "VILLUPURAM",
            "597": "VIRUDHUNAGAR",
            "610": "Ariyalur",
            "634": "TIRUPPUR",
            "729": "KALLAKURICHI",
            "730": "CHENGALPATTU",
            "731": "Ranipet",
            "732": "Tirupathur",
            "733": "TENKASI",
            "735": "Mayiladuthurai",
        }
    },
    "34": {
        state_name: "PUDUCHERRY",
        districts: {
            "598": "KARAIKAL",
            "600": "PONDICHERRY"
        }
    },
    "35": {
        state_name: "ANDAMAN AND NICOBAR",
        districts: {
            "602": "SOUTH ANDAMANS",
            "603": "NICOBARS",
            "632": "NORTH AND MIDDLE ANDAMAN"
        }
    },
    "36": {
        state_name: "TELANGANA",
        districts: {
            "501": "ADILABAD",
            "507": "HYDERABAD",
            "508": "KARIMNAGAR",
            "509": "KHAMMAM",
            "512": "MAHABUBNAGAR",
            "513": "MEDAK",
            "514": "NALGONDA",
            "516": "NIZAMABAD",
            "518": "RANGA REDDY",
            "519": "WARANGAL",
            "680": "Nirmal",
            "681": "Jagitial",
            "682": "PEDDAPALLI",
            "683": "RAJANNA SIRCILLA",
            "684": "MANCHERIAL",
            "685": "KAMAREDDY",
            "686": "HANUMAKONDA",
            "687": "JAYASHANKAR BHUPALAPALLY",
            "688": "MAHABUBABAD",
            "689": "JANGOAN",
            "690": "BHADRADRI KOTHAGUDEM",
            "691": "SANGAREDDY",
            "692": "SIDDIPET",
            "693": "WANAPARTHY",
            "694": "NAGARKURNOOL",
            "695": "JOGULAMBA GADWAL",
            "696": "SURYAPET",
            "697": "YADADRI BHUVANAGIRI",
            "698": "VIKARABAD",
            "699": "KUMURAM BHEEM ASIFABAD",
            "700": "MEDCHAL MALKAJGIRI",
            "720": "Mulugu",
            "721": "Narayanpet",
        }
    },
    "37": {
        state_name: "LADAKH",
        districts: {
            "06": "KARGIL",
            "09": "LEH LADAKH",
        }
    },
    "38": {
        state_name: "THE DADRA AND NAGAR HAVELI AND DAMAN AND DIU",
        districts: {
            "463": "DAMAN",
            "464": "DIU",
            "465": "DADRA AND NAGAR HAVELI"
        }
    },
}

const LGD_TO_DISTRICT = {
    "1": "ANANTNAG",
    "2": "Budgam",
    "3": "BARAMULLA",
    "4": "DODA",
    "5": "JAMMU",
    "7": "KATHUA",
    "8": "KUPWARA",
    "10": "POONCH",
    "11": "PULWAMA",
    "12": "RAJOURI",
    "13": "SRINAGAR",
    "14": "UDHAMPUR",
    "620": "KISHTWAR",
    "621": "RAMBAN",
    "622": "KULGAM",
    "623": "BANDIPORA",
    "624": "SAMBA",
    "625": "SHOPIAN",
    "626": "GANDERBAL",
    "627": "REASI",
    "15": "BILASPUR",
    "16": "CHAMBA",
    "17": "HAMIRPUR",
    "18": "KANGRA",
    "19": "KINNAUR",
    "20": "KULLU",
    "21": "LAHUL AND SPITI",
    "22": "MANDI",
    "23": "SHIMLA",
    "24": "SIRMAUR",
    "25": "SOLAN",
    "26": "UNA",
    "27": "AMRITSAR",
    "28": "BATHINDA",
    "29": "FARIDKOT",
    "30": "FATEHGARH SAHIB",
    "31": "FEROZEPUR",
    "32": "GURDASPUR",
    "33": "HOSHIARPUR",
    "34": "JALANDHAR",
    "35": "KAPURTHALA",
    "36": "LUDHIANA",
    "37": "MANSA",
    "38": "MOGA",
    "39": "SRI MUKTSAR SAHIB",
    "40": "Shahid Bhagat Singh Nagar",
    "41": "PATIALA",
    "42": "RUPNAGAR",
    "43": "SANGRUR",
    "605": "BARNALA",
    "608": "S.A.S Nagar",
    "609": "Tarn Taran",
    "651": "FAZILKA",
    "662": "PATHANKOT",
    "737": "MALERKOTLA",
    "45": "ALMORA",
    "46": "BAGESHWAR",
    "47": "CHAMOLI",
    "48": "CHAMPAWAT",
    "49": "DEHRADUN",
    "50": "HARIDWAR",
    "51": "NAINITAL",
    "52": "PAURI GARHWAL",
    "53": "PITHORAGARH",
    "54": "RUDRA PRAYAG",
    "55": "TEHRI GARHWAL",
    "56": "UDAM SINGH NAGAR",
    "57": "UTTAR KASHI",
    "58": "AMBALA",
    "59": "BHIWANI",
    "60": "FARIDABAD",
    "61": "FATEHABAD",
    "62": "GURUGRAM",
    "63": "HISAR",
    "64": "JHAJJAR",
    "65": "JIND",
    "66": "KAITHAL",
    "67": "KARNAL",
    "68": "KURUKSHETRA",
    "69": "MAHENDRAGARH",
    "70": "PANCHKULA",
    "71": "PANIPAT",
    "72": "REWARI",
    "73": "ROHTAK",
    "74": "SIRSA",
    "75": "SONIPAT",
    "76": "YAMUNANAGAR",
    "604": "NUH",
    "619": "PALWAL",
    "701": "CHARKI DADRI",
    "77": "CENTRAL",
    "78": "EAST",
    "79": "NEW DELHI",
    "80": "NORTH",
    "81": "NORTH EAST",
    "82": "NORTH WEST",
    "83": "SOUTH",
    "84": "SOUTH WEST",
    "85": "WEST",
    "670": "South East",
    "671": "SHAHDARA",
    "86": "AJMER",
    "87": "ALWAR",
    "88": "BANSWARA",
    "89": "BARAN",
    "90": "BARMER",
    "91": "BHARATPUR",
    "92": "BHILWARA",
    "93": "BIKANER",
    "94": "BUNDI",
    "95": "CHITTORGARH",
    "96": "CHURU",
    "97": "DAUSA",
    "98": "DHOLPUR",
    "99": "DUNGARPUR",
    "100": "GANGANAGAR",
    "101": "HANUMANGARH",
    "102": "JAIPUR",
    "103": "JAIPUR",
    "104": "JALORE",
    "105": "JHALAWAR",
    "106": "JHUNJHUNU",
    "107": "JODHPUR",
    "108": "KARAULI",
    "109": "KOTA",
    "110": "NAGAUR",
    "111": "PALI",
    "112": "RAJSAMAND",
    "113": "SAWAI MADHOPUR",
    "114": "SIKAR",
    "115": "SIROHI",
    "116": "TONK",
    "117": "UDAIPUR",
    "629": "PRATAPGARH",
    "772": "Phalodi",
    "774": "Beawar",
    "768": "Didwana-Kuchaman",
    "782": "Kotputli-Behror",
    "777": "Salumbar",
    "775": "Balotra",
    "767": "Deeg",
    "770": "Khairthal-Tijara",
    "118": "AGRA",
    "119": "ALIGARH",
    "120": "PRAYAGRAJ",
    "121": "AMBEDKAR NAGAR",
    "122": "AURAIYA",
    "123": "AZAMGARH",
    "124": "BAGHPAT",
    "125": "BAHRAICH",
    "126": "BALLIA",
    "127": "BALRAMPUR",
    "128": "BANDA",
    "129": "BARABANKI",
    "130": "BAREILLY",
    "131": "BASTI",
    "132": "BIJNOR",
    "133": "BUDAUN",
    "134": "BULANDSHAHR",
    "135": "CHANDAULI",
    "136": "CHITRAKOOT",
    "137": "DEORIA",
    "138": "ETAH",
    "139": "ETAWAH",
    "140": "AYODHYA",
    "141": "FARRUKHABAD",
    "142": "FATEHPUR",
    "143": "FIROZABAD",
    "144": "GAUTAM BUDDHA NAGAR",
    "145": "GHAZIABAD",
    "146": "GHAZIPUR",
    "147": "GONDA",
    "148": "GORAKHPUR",
    "149": "HAMIRPUR",
    "150": "HARDOI",
    "151": "JALAUN",
    "152": "JAUNPUR",
    "153": "JHANSI",
    "154": "AMROHA",
    "155": "KANNAUJ",
    "156": "KANPUR DEHAT",
    "157": "KANPUR NAGAR",
    "158": "KAUSHAMBI",
    "159": "KHERI",
    "160": "KUSHI NAGAR",
    "161": "LALITPUR",
    "162": "LUCKNOW",
    "163": "HATHRAS",
    "164": "MAHARAJGANJ",
    "165": "MAHOBA",
    "166": "MAINPURI",
    "167": "MATHURA",
    "168": "MAU",
    "169": "MEERUT",
    "170": "MIRZAPUR",
    "171": "MORADABAD",
    "172": "MUZAFFARNAGAR",
    "173": "PILIBHIT",
    "174": "PRATAPGARH",
    "175": "RAE BARELI",
    "176": "RAMPUR",
    "177": "SAHARANPUR",
    "178": "SANT KABEER NAGAR",
    "179": "BHADOHI",
    "180": "SHAHJAHANPUR",
    "181": "SHRAVASTI",
    "182": "SIDDHARTH NAGAR",
    "183": "SITAPUR",
    "184": "SONBHADRA",
    "185": "SULTANPUR",
    "186": "UNNAO",
    "187": "VARANASI",
    "633": "Kasganj",
    "640": "Amethi",
    "659": "SAMBHAL",
    "660": "SHAMLI",
    "661": "HAPUR",
    "188": "ARARIA",
    "189": "AURANGABAD",
    "190": "BANKA",
    "191": "BEGUSARAI",
    "192": "BHAGALPUR",
    "193": "BHOJPUR",
    "194": "BUXAR",
    "195": "DARBHANGA",
    "196": "GAYA",
    "197": "GOPALGANJ",
    "198": "JAMUI",
    "199": "JEHANABAD",
    "200": "KAIMUR (BHABUA)",
    "201": "KATIHAR",
    "202": "KHAGARIA",
    "203": "KISHANGANJ",
    "204": "LAKHISARAI",
    "205": "MADHEPURA",
    "206": "MADHUBANI",
    "207": "MUNGER",
    "208": "MUZAFFARPUR",
    "209": "NALANDA",
    "210": "NAWADA",
    "211": "PASHCHIM CHAMPARAN",
    "212": "PATNA",
    "213": "PURBI CHAMPARAN",
    "214": "PURNIA",
    "215": "ROHTAS",
    "216": "SAHARSA",
    "217": "SAMASTIPUR",
    "218": "SARAN",
    "219": "SHEIKHPURA",
    "220": "SHEOHAR",
    "221": "SITAMARHI",
    "222": "SIWAN",
    "223": "SUPAUL",
    "224": "VAISHALI",
    "611": "ARWAL",
    "225": "Gangtok",
    "226": "Mangan",
    "227": "Namchi",
    "228": "Gyalshing",
    "741": "Pakyong",
    "742": "Soreng",
    "229": "CHANGLANG",
    "230": "DIBANG VALLEY",
    "231": "EAST KAMENG",
    "232": "EAST SIANG",
    "233": "KURUNG KUMEY",
    "234": "LOHIT",
    "235": "LOWER DIBANG VALLEY",
    "236": "LOWER SUBANSIRI",
    "237": "PAPUM PARE",
    "238": "TAWANG",
    "239": "TIRAP",
    "240": "UPPER SIANG",
    "241": "UPPER SUBANSIRI",
    "242": "WEST KAMENG",
    "243": "WEST SIANG",
    "628": "ANJAW",
    "666": "LONGDING",
    "677": "KRA DAADI",
    "678": "NAMSAI",
    "679": "SIANG",
    "718": "KAMLE",
    "719": "LOWER SIANG",
    "723": "PAKKE KESSANG",
    "724": "LEPARADA",
    "725": "SHI YOMI",
    "244": "DIMAPUR",
    "245": "KOHIMA",
    "246": "MOKOKCHUNG",
    "247": "MON",
    "248": "PHEK",
    "249": "TUENSANG",
    "250": "WOKHA",
    "251": "ZUNHEBOTO",
    "613": "PEREN",
    "614": "KIPHIRE",
    "615": "LONGLENG",
    "736": "Noklak",
    "757": "Tseminyu",
    "758": "Chumoukedima",
    "252": "BISHNUPUR",
    "253": "CHANDEL",
    "254": "CHURACHANDPUR",
    "255": "IMPHAL EAST",
    "256": "IMPHAL WEST",
    "257": "SENAPATI",
    "258": "TAMENGLONG",
    "259": "THOUBAL",
    "260": "UKHRUL",
    "711": "KAKCHING",
    "712": "KAKCHING",
    "713": "JIRIBAM",
    "714": "NONEY",
    "715": "PHERZAWL",
    "716": "TENGNOUPAL",
    "717": "KAMJONG",
    "261": "AIZAWL",
    "262": "CHAMPHAI",
    "263": "KOLASIB",
    "264": "LAWNGTLAI",
    "265": "LUNGLEI",
    "266": "MAMIT",
    "267": "SAIHA",
    "268": "SERCHHIP",
    "726": "Hnahthial",
    "727": "SAITUAL",
    "728": "KHAWZAWL",
    "269": "Dhalai",
    "270": "North Tripura",
    "271": "South Tripura",
    "272": "West Tripura",
    "652": "Khowai",
    "653": "Sepahijala",
    "654": "Gomati",
    "655": "Unakoti",
    "273": "EAST GARO HILLS",
    "274": "NEAST KHASI HILLS",
    "275": "WEST JAINTIA HILLS",
    "276": "RI BHOI",
    "277": "SOUTH GARO HILLS",
    "278": "WEST GARO HILLS",
    "279": "WEST KHASI HILLS",
    "656": "NORTH GARO HILLS",
    "657": "EAST JAINTIA HILLS",
    "658": "SOUTH WEST KHASI HILLS",
    "663": "SOUTH WEST GARO HILLS",
    "740": "EASTERN WEST KHASI HILLS",
    "280": "BARPETA",
    "281": "BONGAIGAON",
    "282": "CACHAR",
    "283": "DARRANG",
    "284": "DHEMAJI",
    "285": "DHUBRI",
    "286": "DIBRUGARH",
    "287": "GOALPARA",
    "288": "GOLAGHAT",
    "289": "HAILAKANDI",
    "290": "JORHAT",
    "291": "KAMRUP",
    "292": "KARBI ANGLONG",
    "293": "KARIMGANJ",
    "294": "KOKRAJHAR",
    "295": "LAKHIMPUR",
    "296": "MARIGAON",
    "297": "NAGAON",
    "298": "NALBARI",
    "299": "DIMA HASAO",
    "300": "SIVASAGAR",
    "301": "SONITPUR",
    "302": "TINSUKIA",
    "612": "CHIRANG",
    "616": "BAKSA",
    "617": "UDALGURI",
    "618": "KAMRUP METRO",
    "705": "Biswanath",
    "706": "MAJULI",
    "707": "SOUTH SALMARA MANCACHAR",
    "708": "CHARAIDEO",
    "709": "HOJAI",
    "710": "WEST KARBI ANGLONG",
    "739": "BAJALI",
    "756": "TAMULPUR",
    "303": "24 PARAGANAS NORTH",
    "304": "24 PARAGANAS SOUTH",
    "305": "BANKURA",
    "306": "PURBA BARDHAMAN",
    "307": "BIRBHUM",
    "308": "COOCHBEHAR",
    "309": "DARJEELING",
    "310": "DINAJPUR DAKSHIN",
    "311": "DINAJPUR UTTAR",
    "312": "HOOGHLY",
    "313": "HOWRAH",
    "314": "JALPAIGURI",
    "316": "MALDAH",
    "317": "MEDINIPUR EAST",
    "318": "MEDINIPUR WEST",
    "319": "MURSHIDABAD",
    "320": "NADIA",
    "321": "PURULIA",
    "664": "Alipurduar",
    "702": "KALIMPONG",
    "703": "KALIMPONG",
    "704": "PASCHIM BARDHAMAN",
    "322": "BOKARO",
    "323": "BOKARO",
    "324": "DEOGHAR",
    "325": "DEOGHAR",
    "326": "DUMKA",
    "327": "EAST SINGHBUM",
    "328": "GARHWA",
    "329": "GIRIDIH",
    "330": "GODDA",
    "331": "GUMLA",
    "332": "HAZARIBAGH",
    "333": "JAMTARA",
    "334": "KODERMA",
    "335": "LATEHAR",
    "336": "LOHARDAGA",
    "337": "PAKUR",
    "338": "PALAMU",
    "339": "RANCHI",
    "340": "SAHEBGANJ",
    "341": "SARAIKELA KHARSAWAN",
    "342": "SIMDEGA",
    "343": "WEST SINGHBHUM",
    "606": "KHUNTI",
    "607": "RAMGARH",
    "322": "BOKARO",
    "323": "BOKARO",
    "324": "DEOGHAR",
    "325": "DEOGHAR",
    "326": "DUMKA",
    "327": "EAST SINGHBUM",
    "328": "GARHWA",
    "329": "GIRIDIH",
    "330": "GODDA",
    "331": "GUMLA",
    "332": "HAZARIBAGH",
    "333": "JAMTARA",
    "334": "KODERMA",
    "335": "LATEHAR",
    "336": "LOHARDAGA",
    "337": "PAKUR",
    "338": "PALAMU",
    "339": "RANCHI",
    "340": "SAHEBGANJ",
    "341": "SARAIKELA KHARSAWAN",
    "342": "SIMDEGA",
    "343": "WEST SINGHBHUM",
    "606": "KHUNTI",
    "607": "RAMGARH",
    "369": "PURI",
    "344": "ANUGUL",
    "345": "BALANGIR",
    "346": "BALESHWAR",
    "347": "BARGARH",
    "348": "BHADRAK",
    "349": "BOUDH",
    "350": "CUTTACK",
    "351": "DEOGARH",
    "352": "DHENKANAL",
    "353": "GAJAPATI",
    "354": "GANJAM",
    "355": "JAGATSINGHAPUR",
    "356": "JAJAPUR",
    "357": "JHARSUGUDA",
    "358": "KALAHANDI",
    "359": "KANDHAMAL",
    "360": "KENDRAPARA",
    "361": "KENDUJHAR",
    "362": "KHORDHA",
    "363": "KORAPUT",
    "364": "MALKANGIRI",
    "365": "MAYURBHANJ",
    "366": "NABARANGPUR",
    "367": "NAYAGARH",
    "368": "NUAPADA",
    "370": "RAYAGADA",
    "371": "SAMBALPUR",
    "372": "SONEPUR",
    "373": "SUNDARGARH",
    "374": "BASTAR",
    "375": "BILASPUR",
    "376": "DANTEWADA",
    "377": "DHAMTARI",
    "378": "DURG",
    "379": "JANJGIR-CHAMPA",
    "380": "JASHPUR",
    "381": "KANKER",
    "382": "KABIRDHAM",
    "383": "KORBA",
    "384": "KOREA",
    "385": "MAHASAMUND",
    "386": "RAIGARH",
    "387": "RAIPUR",
    "388": "RAJNANDGAON",
    "389": "SURGUJA",
    "636": "BIJAPUR",
    "637": "NARAYANPUR",
    "642": "SUKMA",
    "643": "KONDAGAON",
    "644": "BALODA BAZAR",
    "645": "GARIYABAND",
    "646": "BALOD",
    "647": "MUNGELI",
    "648": "SURAJPUR",
    "649": "BALRAMPUR",
    "650": "BEMETARA",
    "734": "Gaurella Pendra Marwahi",
    "759": "KHAIRGARH CHHUIKHADAN GANDAI",
    "760": "MANENDRAGARH CHIRIMIRI BHARATPUR",
    "761": "MOHLA MANPUR AMBAGARH CHOUKI",
    "762": "SAKTI",
    "763": "SARANGARH BILAIGARH",
    "390": "ANUPPUR",
    "391": "ASHOKNAGAR",
    "392": "BALAGHAT",
    "393": "BARWANI",
    "394": "BETUL",
    "395": "BHIND",
    "396": "BHOPAL",
    "397": "BURHANPUR",
    "398": "CHHATARPUR",
    "399": "CHHINDWARA",
    "400": "DAMOH",
    "401": "DATIA",
    "402": "DEWAS",
    "403": "DHAR",
    "404": "DINDORI",
    "405": "EAST NIMAR",
    "406": "GUNA",
    "407": "GWALIOR",
    "408": "HARDA",
    "409": "NARMADAPURAM",
    "410": "INDORE",
    "411": "JABALPUR",
    "412": "JHABUA",
    "413": "KATNI",
    "414": "KHARGONE",
    "415": "MANDLA",
    "416": "MANDSAUR",
    "417": "MORENA",
    "418": "NARSINGHPUR",
    "419": "NEEMUCH",
    "420": "PANNA",
    "421": "RAISEN",
    "422": "RAJGARH",
    "423": "RATLAM",
    "424": "REWA",
    "425": "SAGAR",
    "426": "SATNA",
    "427": "SEHORE",
    "428": "SEONI",
    "429": "SHAHDOL",
    "430": "SHAJAPUR",
    "431": "SHEOPUR",
    "432": "SHIVPURI",
    "433": "SIDHI",
    "434": "TIKAMGARH",
    "435": "UJJAIN",
    "436": "UMARIA",
    "437": "VIDISHA",
    "438": "SINGRAULI",
    "439": "ALIRAJPUR",
    "667": "AGAR MALWA",
    "766": "MAUGANJ",
    "785": "Pandhurna",
    "784": "Maihar",
    "439": "AMRELI",
    "440": "ANAND",
    "441": "BANAS KANTHA",
    "442": "BHARUCH",
    "443": "BHAVNAGAR",
    "444": "DANG",
    "445": "DOHAD",
    "446": "GANDHINAGAR",
    "447": "JAMNAGAR",
    "448": "JUNAGADH",
    "449": "KACHCHH",
    "450": "KHEDA",
    "451": "MAHESANA",
    "452": "NARMADA",
    "453": "NAVSARI",
    "454": "PANCH MAHALS",
    "455": "PATAN",
    "456": "PORBANDAR",
    "457": "RAJKOT",
    "458": "SABAR KANTHA",
    "459": "SURAT",
    "460": "SURENDRANAGAR",
    "461": "VADODARA",
    "462": "VALSAD",
    "641": "TAPI",
    "668": "CHHOTAUDEPUR",
    "669": "Mahisagar",
    "672": "ARVALLI",
    "673": "MORBI",
    "674": "DEVBHUMI DWARKA",
    "675": "GIR SOMNATH",
    "676": "BOTAD",
    "438": "AHMEDABAD",
    "466": "AHMEDNAGAR",
    "467": "AKOLA",
    "468": "AMRAVATI",
    "469": "AURANGABAD",
    "470": "BEED",
    "471": "BHANDARA",
    "472": "BULDHANA",
    "473": "CHANDRAPUR",
    "474": "DHULE",
    "475": "GADCHIROLI",
    "476": "GONDIA",
    "477": "HINGOLI",
    "478": "JALGAON",
    "479": "JALNA",
    "480": "KOLHAPUR",
    "481": "LATUR",
    "483": "MUMBAI SUBURBAN",
    "484": "NAGPUR",
    "485": "NANDED",
    "486": "NANDURBAR",
    "487": "NASHIK",
    "488": "OSMANABAD",
    "489": "PARBHANI",
    "490": "PUNE",
    "491": "RAIGAD",
    "492": "RATNAGIRI",
    "493": "SANGLI",
    "494": "SATARA",
    "495": "SINDHUDURG",
    "496": "SOLAPUR",
    "497": "THANE",
    "498": "WARDHA",
    "499": "WASHIM",
    "500": "YAVATMAL",
    "665": "PALGHAR",
    "502": "ANANTAPUR",
    "503": "CHITTOOR",
    "504": "Y.S.R.",
    "505": "EAST GODAVARI",
    "506": "GUNTUR",
    "510": "KRISHNA",
    "511": "KURNOOL",
    "515": "SPSR NELLORE",
    "517": "PRAKASAM",
    "519": "SRIKAKULAM",
    "520": "VISAKHAPATANAM",
    "521": "VIZIANAGARAM",
    "523": "WEST GODAVARI",
    "743": "Parvathipuram Manyam",
    "744": "Anakapalli",
    "745": "Alluri Sitharama Raju",
    "746": "Kakinada",
    "747": "Konaseema",
    "748": "Eluru",
    "749": "NTR",
    "750": "Bapatla",
    "751": "Palnadu",
    "752": "Tirupati",
    "753": "Annamayya",
    "754": "Sri Sathya Sai",
    "755": "Nandyal",
    "524": "BAGALKOTE",
    "525": "BENGALURU URBAN",
    "526": "BENGALURU RURAL",
    "527": "BELAGAVI",
    "528": "BALLARI",
    "529": "BIDAR",
    "530": "VIJAYAPURA",
    "531": "CHAMARAJANAGARA",
    "532": "CHIKKAMAGALURU",
    "533": "CHITRADURGA",
    "534": "DAKSHINA KANNADA",
    "535": "DAVANGERE",
    "536": "DHARWAD",
    "537": "GADAG",
    "538": "KALABURAGI",
    "539": "HASSAN",
    "540": "HAVERI",
    "541": "KODAGU",
    "542": "KOLAR",
    "543": "KOPPAL",
    "544": "MANDYA",
    "545": "MYSURU",
    "546": "RAICHUR",
    "547": "SHIVAMOGGA",
    "548": "TUMAKURU",
    "549": "UDUPI",
    "550": "UTTARA KANNADA",
    "630": "CHIKKABALLAPURA",
    "631": "RAMANAGARA",
    "635": "YADGIR",
    "738": "VIJAYANAGAR",
    "551": "NORTH GOA",
    "552": "SOUTH GOA",
    "553": "LAKSHADWEEP DISTRICT",
    "554": "ALAPPUZHA",
    "555": "ERNAKULAM",
    "556": "IDUKKI",
    "557": "KANNUR",
    "558": "KASARAGOD",
    "559": "KOLLAM",
    "560": "KOTTAYAM",
    "561": "KOZHIKODE",
    "562": "MALAPPURAM",
    "563": "PALAKKAD",
    "564": "PATHANAMTHITTA",
    "565": "THIRUVANANTHAPURAM",
    "566": "THRISSUR",
    "567": "WAYANAD",
    "568": "CHENNAI",
    "569": "COIMBATORE",
    "570": "CUDDALORE",
    "571": "DHARMAPURI",
    "572": "DINDIGUL",
    "573": "ERODE",
    "574": "KANCHIPURAM",
    "575": "KANNIYAKUMARI",
    "576": "KARUR",
    "577": "KRISHNAGIRI",
    "578": "MADURAI",
    "579": "NAGAPATTINAM",
    "580": "NAMAKKAL",
    "581": "PERAMBALUR",
    "582": "PUDUKKOTTAI",
    "583": "RAMANATHAPURAM",
    "584": "SALEM",
    "585": "SIVAGANGA",
    "586": "THANJAVUR",
    "587": "THE NILGIRIS",
    "588": "THENI",
    "589": "THIRUVALLUR",
    "590": "THIRUVARUR",
    "591": "TIRUCHIRAPPALLI",
    "592": "TIRUNELVELI",
    "593": "TIRUVANNAMALAI",
    "594": "TUTICORIN",
    "595": "VELLORE",
    "596": "VILLUPURAM",
    "597": "VIRUDHUNAGAR",
    "610": "Ariyalur",
    "634": "TIRUPPUR",
    "729": "KALLAKURICHI",
    "730": "CHENGALPATTU",
    "731": "Ranipet",
    "732": "Tirupathur",
    "733": "TENKASI",
    "735": "Mayiladuthurai",
    "598": "KARAIKAL",
    "600": "PONDICHERRY",
    "602": "SOUTH ANDAMANS",
    "603": "NICOBARS",
    "632": "NORTH AND MIDDLE ANDAMAN",
    "501": "ADILABAD",
    "507": "HYDERABAD",
    "508": "KARIMNAGAR",
    "509": "KHAMMAM",
    "512": "MAHABUBNAGAR",
    "513": "MEDAK",
    "514": "NALGONDA",
    "516": "NIZAMABAD",
    "518": "RANGA REDDY",
    "519": "WARANGAL",
    "680": "Nirmal",
    "681": "Jagitial",
    "682": "PEDDAPALLI",
    "683": "RAJANNA SIRCILLA",
    "684": "MANCHERIAL",
    "685": "KAMAREDDY",
    "686": "HANUMAKONDA",
    "687": "JAYASHANKAR BHUPALAPALLY",
    "688": "MAHABUBABAD",
    "689": "JANGOAN",
    "690": "BHADRADRI KOTHAGUDEM",
    "691": "SANGAREDDY",
    "692": "SIDDIPET",
    "693": "WANAPARTHY",
    "694": "NAGARKURNOOL",
    "695": "JOGULAMBA GADWAL",
    "696": "SURYAPET",
    "697": "YADADRI BHUVANAGIRI",
    "698": "VIKARABAD",
    "699": "KUMURAM BHEEM ASIFABAD",
    "700": "MEDCHAL MALKAJGIRI",
    "720": "Mulugu",
    "721": "Narayanpet",
    "6": "KARGIL",
    "9": "LEH LADAKH",
    "463": "DAMAN",
    "464": "DIU",
    "465": "DADRA AND NAGAR HAVELI"
}

export  {
    LGD_TO_STATE,
    LGD_TO_DISTRICT
}